### PR TITLE
Add header file for `unlink`

### PR DESCRIPTION
**Pull request by einola**
Please consider this minor bug fix for mapx. Thank you for the code :)

This commit adds an include statement for `unistd.h` to grid_io.c, defining the `unlink` function. Without this, the code does not compile on Apple clang version 13.1.6 (clang-1316.0.21.2.5), with the following error message:

grid_io.c:101:7: error: implicit declaration of function 'unlink' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      unlink(filename);
      ^

### CODE REVIEW

**Review by mjbrodzik — COMMENTED** [review]
Hello, @einola, thank you for the pull request.
As you can tell, we don't do much maintenance on this package anymore.
We were unaware of the reserved word issue on variable "this", thank you for finding that.
My only question is whether include on unistd.h should be conditional for Apple environments only? 
Mary Jo

**Review by mjbrodzik — APPROVED** [review]
Looks like unistd.h should be available on any POSIX-compliant system.  Please ignore my last question.

**Comment by einola** [comment]
Ok, great! I can put in a pull request for "this", once you've merged this one.

Cheers, Einar

**Comment by mjbrodzik** [comment]
@flamingbear  and @kbeamnsidc do you guys have any objections if we merge these changes from Einar back to master branch on mapx?  
I don't have time to make a new tarball and patch, but it looks to me like somebody got rid of all that on the migration to github.  What is the current workflow for new release?  update main branch and ReleaseNotes?  Anything else?

**Comment by flamingbear** [comment]
I don't have any issues with merging these.  Who owns this now?  They can submit a ticket to get a new release done.  The last tag is v0.13, but I don't know what our last tarball was since the link https://nsidc.org/data/tools is dead.
